"""create relationship between the pitch class and category class

Revision ID: 5864aefae095
Revises: 0828087435bc
Create Date: 2018-05-22 09:28:56.262145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5864aefae095'
down_revision = '0828087435bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('pitches_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pitches', 'pitches', ['pitches_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pitches', type_='foreignkey')
    op.drop_column('pitches', 'pitches_id')
    # ### end Alembic commands ###
